// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxfuovyrqqyzfaiqnacf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94ZnVvdnlycXF5emZhaXFuYWNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MDU4MDMsImV4cCI6MjA2MDE4MTgwM30.KoJWsv-lNGKHvBqD9s-izwWGIRbGdXksLVoYTOKK8kA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);